using CampaignSystem.Configuration;
using CampaignSystem.Data;
using CampaignSystem.DTOs;
using CampaignSystem.Entities;
using CampaignSystem.Enums;
using CampaignSystem.Services.Caching;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System.Text.RegularExpressions;

namespace CampaignSystem.Services;

/// <summary>
/// A campaign's terms: the sentences an operator sees on the definition screen and, through
/// the catalog, the customer eventually reads. Three jobs live here — persisting an
/// operator's hand-edited list, regenerating the auto lines from the campaign's own rules and
/// criteria, and previewing those same lines for a draft that has no database row yet.
///
/// Split out of <see cref="CampaignService"/>: campaign CRUD changes for one set of reasons,
/// the wording/template concern for another. Both still evict the shared
/// <see cref="CampaignCatalog"/>, since a changed term changes what the customer list shows.
///
/// The sentences read the same fields <see cref="RewardService"/> qualifies transactions on,
/// so the wording never claims a restriction the reward engine does not actually enforce.
/// </summary>
public class CampaignConditionService(
    CampaignDbContext context,
    CampaignCatalogCache catalogCache,
    IOptions<RewardCalculationOptions> rewardOptions,
    ILogger<CampaignConditionService> logger)
    : ICampaignConditionService
{
    public async Task<List<CampaignConditionDto>?> GetConditionsAsync(
        int campaignId,
        CancellationToken cancellationToken = default)
    {
        var campaignExists = await context.Campaigns
            .AnyAsync(c => c.Id == campaignId && c.IsActive, cancellationToken);

        return campaignExists ? await LoadConditionsAsync(campaignId, cancellationToken) : null;
    }

    public async Task<bool> SetConditionsAsync(
        int campaignId,
        List<CampaignConditionDto> conditions,
        CancellationToken cancellationToken = default)
    {
        var campaignExists = await context.Campaigns
            .AnyAsync(c => c.Id == campaignId && c.IsActive, cancellationToken);

        if (!campaignExists)
        {
            return false;
        }

        var existing = await context.CampaignConditions
            .Where(x => x.CampaignId == campaignId)
            .ToListAsync(cancellationToken);

        context.CampaignConditions.RemoveRange(existing);

        context.CampaignConditions.AddRange(conditions.Select((c, index) => new CampaignCondition
        {
            CampaignId = campaignId,
            Text = c.Text,
            DisplayOrder = index,
            IsAutoGenerated = c.IsAutoGenerated
        }));

        await context.SaveChangesAsync(cancellationToken);
        catalogCache.Invalidate();

        logger.LogInformation("Campaign {CampaignId} conditions updated.", campaignId);

        return true;
    }

    public async Task<List<CampaignConditionDto>?> GenerateConditionsAsync(
        int campaignId,
        CancellationToken cancellationToken = default)
    {
        var campaign = await context.Campaigns
            .FirstOrDefaultAsync(c => c.Id == campaignId && c.IsActive, cancellationToken);

        if (campaign is null)
        {
            return null;
        }

        var generatedTexts = await BuildAutoConditionTextsAsync(campaign, cancellationToken);

        // Only the rows the previous run generated are replaced. A line an operator wrote
        // by hand is not this method's to touch.
        var previousAuto = await context.CampaignConditions
            .Where(x => x.CampaignId == campaignId && x.IsAutoGenerated)
            .ToListAsync(cancellationToken);

        context.CampaignConditions.RemoveRange(previousAuto);

        context.CampaignConditions.AddRange(generatedTexts.Select((text, index) => new CampaignCondition
        {
            CampaignId = campaignId,
            Text = text,
            DisplayOrder = index,
            IsAutoGenerated = true
        }));

        // Hand-written lines always read after the generated ones, in the order they were
        // added — renumbered here since the generated block above may have grown or shrunk.
        var manual = await context.CampaignConditions
            .Where(x => x.CampaignId == campaignId && !x.IsAutoGenerated)
            .OrderBy(x => x.DisplayOrder)
            .ToListAsync(cancellationToken);

        for (var i = 0; i < manual.Count; i++)
        {
            manual[i].DisplayOrder = generatedTexts.Count + i;
        }

        await context.SaveChangesAsync(cancellationToken);
        catalogCache.Invalidate();

        return await LoadConditionsAsync(campaignId, cancellationToken);
    }

    private async Task<List<CampaignConditionDto>> LoadConditionsAsync(
        int campaignId,
        CancellationToken cancellationToken)
        => await context.CampaignConditions
            .AsNoTracking()
            .Where(x => x.CampaignId == campaignId)
            .OrderBy(x => x.DisplayOrder)
            .Select(x => new CampaignConditionDto
            {
                Id = x.Id,
                Text = x.Text,
                DisplayOrder = x.DisplayOrder,
                IsAutoGenerated = x.IsAutoGenerated
            })
            .ToListAsync(cancellationToken);

    /// <summary>
    /// Matches a <c>{TokenName}</c> placeholder inside a <see cref="CampaignConditionTemplate"/>.
    /// </summary>
    private static readonly Regex ConditionTemplateTokenPattern = new(@"\{(\w+)\}", RegexOptions.Compiled);

    /// <summary>
    /// Fills a template's <c>{TokenName}</c> placeholders from <paramref name="tokens"/>.
    /// A placeholder with no matching entry throws rather than being left in the text
    /// verbatim, since that only happens when a template row was hand-edited into a token
    /// the code never sends — better to surface it than show it to a customer.
    /// </summary>
    private static string RenderConditionTemplate(string templateText, IReadOnlyDictionary<string, string> tokens)
        => ConditionTemplateTokenPattern.Replace(templateText, match =>
        {
            var token = match.Groups[1].Value;

            if (!tokens.TryGetValue(token, out var value))
            {
                throw new InvalidOperationException(
                    $"Campaign condition template references unknown token '{{{token}}}'.");
            }

            return value;
        });

    /// <summary>
    /// Turns a campaign's rules and criteria into the sentences an operator would otherwise
    /// have to type by hand. Reads the same fields <see cref="RewardService"/> qualifies
    /// transactions on, so the wording never claims a restriction the reward engine does
    /// not actually enforce.
    ///
    /// The sentences themselves live in <see cref="CampaignConditionTemplate"/>, keyed by the
    /// scenario below that decided the line applies — that decision stays in code, only the
    /// wording is data. A key with no active row (deleted or turned off with
    /// <see cref="CampaignConditionTemplate.IsActive"/>) simply contributes no line.
    /// </summary>
    private async Task<List<string>> BuildAutoConditionTextsAsync(
        Campaign campaign,
        CancellationToken cancellationToken)
    {
        var templates = await context.CampaignConditionTemplates
            .AsNoTracking()
            .Where(x => x.IsActive)
            .ToDictionaryAsync(x => x.Key, cancellationToken);

        var segmentNames = await context.CampaignSegments
            .Where(x => x.CampaignId == campaign.Id)
            .Select(x => x.Segment.SegmentName)
            .ToListAsync(cancellationToken);

        var productNames = await context.CampaignProducts
            .Where(x => x.CampaignId == campaign.Id)
            .Select(x => x.Product.ProductName)
            .ToListAsync(cancellationToken);

        var merchantNames = await context.CampaignMerchants
            .Where(x => x.CampaignId == campaign.Id)
            .Select(x => x.Merchant.MerchantName)
            .ToListAsync(cancellationToken);

        var transactionCodeNames = await context.CampaignTransactionCodes
            .Where(x => x.CampaignId == campaign.Id)
            .Select(x => x.TransactionCode.Name)
            .ToListAsync(cancellationToken);

        var clawbackExemptProductNames = await context.CampaignClawbackExemptProducts
            .Where(x => x.CampaignId == campaign.Id)
            .Select(x => x.Product.ProductName)
            .ToListAsync(cancellationToken);

        return BuildAutoConditionTexts(templates, new ConditionInputs(
            campaign.CampaignType,
            campaign.StartDate,
            campaign.EndDate,
            campaign.MinimumAmount,
            campaign.MaximumAmount,
            campaign.RewardPoint,
            campaign.MaxRewardAmount,
            campaign.AccumulatesPerCard,
            campaign.Gender,
            campaign.CardType,
            campaign.UnusedPointsClawbackEnabled,
            campaign.UnusedPointsClawbackDays,
            segmentNames,
            productNames,
            merchantNames,
            transactionCodeNames,
            clawbackExemptProductNames));
    }

    public async Task<List<string>> PreviewConditionsAsync(
        CampaignConditionsPreviewDto dto,
        CancellationToken cancellationToken = default)
    {
        var templates = await context.CampaignConditionTemplates
            .AsNoTracking()
            .Where(x => x.IsActive)
            .ToDictionaryAsync(x => x.Key, cancellationToken);

        // Unlike the persisted flow, nothing has been saved yet — the campaign's scope is
        // still just a handful of ids the operator picked, so the names are looked up
        // directly rather than through the CampaignSegments/CampaignProducts/... junction
        // tables (which only exist once a campaign row does).
        var segmentNames = await context.Segments
            .Where(x => dto.Criteria.SegmentIds.Contains(x.Id))
            .Select(x => x.SegmentName)
            .ToListAsync(cancellationToken);

        var productNames = await context.Products
            .Where(x => dto.Criteria.ProductIds.Contains(x.Id))
            .Select(x => x.ProductName)
            .ToListAsync(cancellationToken);

        var merchantNames = await context.Merchants
            .Where(x => dto.Criteria.MerchantIds.Contains(x.Id))
            .Select(x => x.MerchantName)
            .ToListAsync(cancellationToken);

        var transactionCodeNames = await context.TransactionCodes
            .Where(x => dto.Criteria.TransactionCodeIds.Contains(x.Id))
            .Select(x => x.Name)
            .ToListAsync(cancellationToken);

        var clawbackExemptProductNames = await context.Products
            .Where(x => dto.Criteria.ClawbackExemptProductIds.Contains(x.Id))
            .Select(x => x.ProductName)
            .ToListAsync(cancellationToken);

        return BuildAutoConditionTexts(templates, new ConditionInputs(
            dto.CampaignType,
            dto.StartDate,
            dto.EndDate,
            dto.MinimumAmount,
            dto.MaximumAmount,
            dto.RewardPoint,
            dto.MaxRewardAmount,
            dto.EarningType == EarningType.CardBased,
            dto.Gender,
            dto.CardType,
            dto.UnusedPointsClawbackEnabled,
            dto.UnusedPointsClawbackDays,
            segmentNames,
            productNames,
            merchantNames,
            transactionCodeNames,
            clawbackExemptProductNames));
    }

    /// <summary>
    /// The campaign-shape values a set of condition sentences is built from. The same fields
    /// whether they come from a saved <see cref="Campaign"/> or an unsaved draft, so both paths
    /// produce identical wording. Bundled into one object so
    /// <see cref="BuildAutoConditionTexts"/> does not carry a seventeen-parameter signature.
    /// </summary>
    private sealed record ConditionInputs(
        CampaignType CampaignType,
        DateTime? StartDate,
        DateTime? EndDate,
        decimal? MinimumAmount,
        decimal? MaximumAmount,
        decimal? RewardPoint,
        decimal? MaxRewardAmount,
        bool AccumulatesPerCard,
        Gender? Gender,
        CardType? CardType,
        bool UnusedPointsClawbackEnabled,
        int? UnusedPointsClawbackDays,
        IReadOnlyList<string> SegmentNames,
        IReadOnlyList<string> ProductNames,
        IReadOnlyList<string> MerchantNames,
        IReadOnlyList<string> TransactionCodeNames,
        IReadOnlyList<string> ClawbackExemptProductNames);

    /// <summary>
    /// The template-rendering core both <see cref="BuildAutoConditionTextsAsync"/> (a saved
    /// campaign) and <see cref="PreviewConditionsAsync"/> (a draft that is not saved yet)
    /// reduce to before calling this. Takes a plain <see cref="ConditionInputs"/> rather than a
    /// <see cref="Campaign"/> so a draft with no database row can produce exactly the same
    /// sentences a saved one would.
    /// </summary>
    private List<string> BuildAutoConditionTexts(
        Dictionary<string, CampaignConditionTemplate> templates,
        ConditionInputs inputs)
    {
        var lines = new List<string>();

        void AddLine(string key, Dictionary<string, string> tokens)
        {
            if (templates.TryGetValue(key, out var template))
            {
                lines.Add(RenderConditionTemplate(template.TemplateText, tokens));
            }
        }

        // A draft with no dates yet has nothing to say here — this only happens on the
        // preview path, since a saved campaign always has both.
        if (inputs.StartDate is not null && inputs.EndDate is not null)
        {
            AddLine("DateRange", new Dictionary<string, string>
            {
                ["StartDate"] = inputs.StartDate.Value.ToString("dd.MM.yyyy"),
                ["EndDate"] = inputs.EndDate.Value.ToString("dd.MM.yyyy")
            });
        }

        if (inputs.CampaignType == CampaignType.EnrollmentRequired)
        {
            AddLine("EnrollmentRequired", []);
        }

        if (inputs.MinimumAmount is not null && inputs.MaximumAmount is not null)
        {
            AddLine("MinAndMaxAmount", new Dictionary<string, string>
            {
                ["MinimumAmount"] = inputs.MinimumAmount.Value.ToString("N0"),
                ["MaximumAmount"] = inputs.MaximumAmount.Value.ToString("N0")
            });
        }
        else if (inputs.MinimumAmount is not null)
        {
            AddLine("MinAmountOnly", new Dictionary<string, string>
            {
                ["MinimumAmount"] = inputs.MinimumAmount.Value.ToString("N0")
            });
        }
        else if (inputs.MaximumAmount is not null)
        {
            AddLine("MaxAmountOnly", new Dictionary<string, string>
            {
                ["MaximumAmount"] = inputs.MaximumAmount.Value.ToString("N0")
            });
        }

        if (inputs.RewardPoint is not null)
        {
            AddLine("RewardPoint", new Dictionary<string, string>
            {
                ["RewardPoint"] = inputs.RewardPoint.Value.ToString("N0")
            });
        }

        if (inputs.MaxRewardAmount is not null)
        {
            var perUnit = inputs.AccumulatesPerCard ? "kart" : "müşteri";
            AddLine("MaxRewardAmount", new Dictionary<string, string>
            {
                ["PerUnit"] = perUnit,
                ["MaxRewardAmount"] = inputs.MaxRewardAmount.Value.ToString("N0")
            });
        }

        if (inputs.Gender is not null)
        {
            var genderText = inputs.Gender == Gender.Female ? "kadın" : "erkek";
            AddLine("Gender", new Dictionary<string, string> { ["GenderText"] = genderText });
        }

        if (inputs.CardType is not null)
        {
            var cardTypeText = inputs.CardType == CardType.Primary ? "asıl" : "ek";
            AddLine("CardType", new Dictionary<string, string> { ["CardTypeText"] = cardTypeText });
        }

        if (inputs.SegmentNames.Count > 0)
        {
            AddLine("SegmentList", new Dictionary<string, string>
            {
                ["Names"] = string.Join(", ", inputs.SegmentNames.OrderBy(n => n))
            });
        }

        if (inputs.ProductNames.Count > 0)
        {
            AddLine("ProductList", new Dictionary<string, string>
            {
                ["Names"] = string.Join(", ", inputs.ProductNames.OrderBy(n => n))
            });
        }

        if (inputs.MerchantNames.Count > 0)
        {
            AddLine("MerchantList", new Dictionary<string, string>
            {
                ["Names"] = string.Join(", ", inputs.MerchantNames.OrderBy(n => n))
            });
        }

        if (inputs.TransactionCodeNames.Count > 0)
        {
            AddLine("TransactionCodeList", new Dictionary<string, string>
            {
                ["Names"] = string.Join(", ", inputs.TransactionCodeNames.OrderBy(n => n))
            });
        }

        // The reclaim date is computed the same way RewardService works out when a campaign's
        // rewards are actually loaded (end date plus the global loading delay), plus this
        // campaign's own redemption window — so the sentence promises exactly the date the
        // batch will act on, even while the campaign is still running and nothing has been
        // loaded yet.
        if (inputs.UnusedPointsClawbackEnabled && inputs.UnusedPointsClawbackDays is not null && inputs.EndDate is not null)
        {
            var reclaimDate = inputs.EndDate.Value.Date
                .AddDays(rewardOptions.Value.DaysAfterCampaignEnd)
                .AddDays(inputs.UnusedPointsClawbackDays.Value);

            AddLine("UnusedPointsClawback", new Dictionary<string, string>
            {
                ["ReclaimDate"] = reclaimDate.ToString("dd.MM.yyyy")
            });

            if (inputs.ClawbackExemptProductNames.Count > 0)
            {
                AddLine("UnusedPointsClawbackExempt", new Dictionary<string, string>
                {
                    ["Names"] = string.Join(", ", inputs.ClawbackExemptProductNames.OrderBy(n => n))
                });
            }
        }

        return lines;
    }
}
