namespace CampaignSystem.DTOs;

/// <summary>
/// One line of a campaign's terms, as the admin screen edits them.
///
/// Used both for reading the current set and for replacing it: a PUT sends back the same
/// shape it received from a GET, with lines reordered, reworded, removed or added freely.
/// </summary>
public class CampaignConditionDto
{
    /// <summary>0 for a line that does not exist yet — the id a new line gets on save.</summary>
    public int Id { get; set; }

    public string Text { get; set; } = null!;

    /// <summary>Where this line sits among the others. Lower comes first.</summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// False for a line the operator typed in by hand. Regenerating leaves those lines
    /// alone and only replaces the ones this is true for.
    /// </summary>
    public bool IsAutoGenerated { get; set; }
}
