namespace CampaignSystem.Entities;

/// <summary>
/// One bullet point of a campaign's terms as shown to the customer. Maps to
/// CAMPAIGN_CONDITION.
///
/// Generated from the campaign's own rules when an operator asks for it — typically right
/// after creating the campaign — so the wording always starts in sync with what the reward
/// engine actually enforces. From there it is a plain editable row: an operator may reword
/// or remove a generated line, or add one of their own, and neither survives a later
/// <see cref="Services.ICampaignService.GenerateConditionsAsync"/> call unless
/// <see cref="IsAutoGenerated"/> says so.
/// </summary>
public class CampaignCondition
{
    public int Id { get; set; }

    public int CampaignId { get; set; }

    public string Text { get; set; } = null!;

    /// <summary>Where this line sits among the others. Lower comes first.</summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// False for a line an operator typed in by hand. Regenerating only ever replaces the
    /// rows where this is true, so a hand-written line is never silently erased.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public Campaign Campaign { get; set; } = null!;
}
