// <auto-generated />
using System;
using CampaignSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampaignSystem.Data.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    [Migration("20260826122839_MakeQualifyingProcRefundAware")]
    partial class MakeQualifyingProcRefundAware
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampaignSystem.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CardType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EarningType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentBasis")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxRewardAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaximumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RefundClawbackDays")
                        .HasColumnType("int");

                    b.Property<bool>("RefundClawbackEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RewardPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EndDate");

                    b.ToTable("CAMPAIGN", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CAMPAIGN_CONDITION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignConditionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CAMPAIGN_CONDITION_TEMPLATE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Key = "DateRange",
                            TemplateText = "Kampanya {StartDate} - {EndDate} tarihleri arasında geçerlidir."
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Key = "EnrollmentRequired",
                            TemplateText = "Kampanyadan yararlanabilmek için kampanyaya katılım sağlanması gerekmektedir."
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Key = "MinAndMaxAmount",
                            TemplateText = "İşlem tutarı {MinimumAmount} TL ile {MaximumAmount} TL arasında olmalıdır."
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Key = "MinAmountOnly",
                            TemplateText = "En az {MinimumAmount} TL tutarında işlem yapılması gerekmektedir."
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Key = "MaxAmountOnly",
                            TemplateText = "İşlem tutarı en fazla {MaximumAmount} TL olmalıdır."
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Key = "RewardPoint",
                            TemplateText = "Uygun her işlem için {RewardPoint} TL Worldpuan kazandırır."
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Key = "MaxRewardAmount",
                            TemplateText = "Kampanya kapsamında {PerUnit} başına en fazla {MaxRewardAmount} TL Worldpuan kazanılabilir."
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Key = "Gender",
                            TemplateText = "Kampanya yalnızca {GenderText} müşteriler için geçerlidir."
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Key = "CardType",
                            TemplateText = "Kampanya yalnızca {CardTypeText} kartlar için geçerlidir."
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Key = "SegmentList",
                            TemplateText = "Kampanya yalnızca şu müşteri gruplarına açıktır: {Names}."
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Key = "ProductList",
                            TemplateText = "Kampanya yalnızca şu kart tiplerinde geçerlidir: {Names}."
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Key = "MerchantList",
                            TemplateText = "Kampanya yalnızca şu üye işyerlerinde yapılan alışverişlerde geçerlidir: {Names}."
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Key = "TransactionCodeList",
                            TemplateText = "Kampanya yalnızca şu işlem türlerinde geçerlidir: {Names}."
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignMerchant", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "MerchantId");

                    b.HasIndex("MerchantId");

                    b.ToTable("CAMPAIGN_MERCHANT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignParticipation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParticipationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId", "CardId")
                        .IsUnique();

                    b.ToTable("CAMPAIGN_PARTICIPATION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignProduct", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CAMPAIGN_PRODUCT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignReward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("QualifyingCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RewardDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RewardPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId", "CardId")
                        .IsUnique()
                        .HasFilter("[RewardType] = 'Earn'");

                    b.ToTable("CAMPAIGN_REWARD", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignSegment", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "SegmentId");

                    b.HasIndex("SegmentId");

                    b.ToTable("CAMPAIGN_SEGMENT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignTransactionCode", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionCodeId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "TransactionCodeId");

                    b.HasIndex("TransactionCodeId");

                    b.ToTable("CAMPAIGN_TRANSACTION_CODE", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CARD", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("SegmentId");

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MerchantCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MerchantNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantCategoryId");

                    b.HasIndex("MerchantNumber")
                        .IsUnique();

                    b.ToTable("MERCHANT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MerchantCategoryId = 2,
                            MerchantName = "Grande Cafe",
                            MerchantNumber = "300145782"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MerchantCategoryId = 2,
                            MerchantName = "Köfteci Yusuf",
                            MerchantNumber = "300912467"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            MerchantCategoryId = 2,
                            MerchantName = "Big Chefs",
                            MerchantNumber = "300558214"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MerchantCategoryId = 3,
                            MerchantName = "Opet",
                            MerchantNumber = "410874193"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MerchantCategoryId = 3,
                            MerchantName = "Shell",
                            MerchantNumber = "410336729"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MerchantCategoryId = 3,
                            MerchantName = "Petrol Ofisi",
                            MerchantNumber = "410771056"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            MerchantCategoryId = 1,
                            MerchantName = "Migros",
                            MerchantNumber = "520419863"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            MerchantCategoryId = 1,
                            MerchantName = "BİM",
                            MerchantNumber = "520684137"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            MerchantCategoryId = 1,
                            MerchantName = "A101",
                            MerchantNumber = "520297540"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            MerchantCategoryId = 7,
                            MerchantName = "Teknosa",
                            MerchantNumber = "610853024"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            MerchantCategoryId = 7,
                            MerchantName = "Vatan Bilgisayar",
                            MerchantNumber = "610140678"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            MerchantCategoryId = 4,
                            MerchantName = "LC Waikiki",
                            MerchantNumber = "710962385"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.MerchantCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("MERCHANT_CATEGORY", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "GDA",
                            CategoryName = "Gıda / Market"
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "RST",
                            CategoryName = "Restoran / Yeme-İçme"
                        },
                        new
                        {
                            Id = 3,
                            CategoryCode = "AKY",
                            CategoryName = "Akaryakıt"
                        },
                        new
                        {
                            Id = 4,
                            CategoryCode = "GYM",
                            CategoryName = "Giyim"
                        },
                        new
                        {
                            Id = 5,
                            CategoryCode = "AYK",
                            CategoryName = "Ayakkabı & Aksesuar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryCode = "KOZ",
                            CategoryName = "Kozmetik"
                        },
                        new
                        {
                            Id = 7,
                            CategoryCode = "ELK",
                            CategoryName = "Elektronik"
                        },
                        new
                        {
                            Id = 8,
                            CategoryCode = "TEL",
                            CategoryName = "Telekomünikasyon / GSM"
                        },
                        new
                        {
                            Id = 9,
                            CategoryCode = "MOB",
                            CategoryName = "Mobilya & Ev Tekstili"
                        },
                        new
                        {
                            Id = 10,
                            CategoryCode = "BYZ",
                            CategoryName = "Beyaz Eşya"
                        },
                        new
                        {
                            Id = 11,
                            CategoryCode = "OTO",
                            CategoryName = "Otomotiv & Oto Bakım"
                        },
                        new
                        {
                            Id = 12,
                            CategoryCode = "ARK",
                            CategoryName = "Araç Kiralama"
                        },
                        new
                        {
                            Id = 13,
                            CategoryCode = "TUR",
                            CategoryName = "Turizm / Seyahat / Otel"
                        },
                        new
                        {
                            Id = 14,
                            CategoryCode = "HVY",
                            CategoryName = "Havayolları / Ulaşım"
                        },
                        new
                        {
                            Id = 15,
                            CategoryCode = "EGT",
                            CategoryName = "Eğitim"
                        },
                        new
                        {
                            Id = 16,
                            CategoryCode = "SGL",
                            CategoryName = "Sağlık / Eczane / Optik"
                        },
                        new
                        {
                            Id = 17,
                            CategoryCode = "SGR",
                            CategoryName = "Sigorta"
                        },
                        new
                        {
                            Id = 18,
                            CategoryCode = "SPR",
                            CategoryName = "Spor"
                        },
                        new
                        {
                            Id = 19,
                            CategoryCode = "KUY",
                            CategoryName = "Kuyumculuk / Saat"
                        },
                        new
                        {
                            Id = 20,
                            CategoryCode = "KRT",
                            CategoryName = "Kırtasiye / Oyuncak"
                        },
                        new
                        {
                            Id = 21,
                            CategoryCode = "YPI",
                            CategoryName = "Yapı & İnşaat"
                        },
                        new
                        {
                            Id = 22,
                            CategoryCode = "EGL",
                            CategoryName = "Eğlence"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("PRODUCT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductCode = "201",
                            ProductName = "Visa Classic"
                        },
                        new
                        {
                            Id = 2,
                            ProductCode = "202",
                            ProductName = "MasterCard Classic"
                        },
                        new
                        {
                            Id = 3,
                            ProductCode = "203",
                            ProductName = "Visa Gold"
                        },
                        new
                        {
                            Id = 4,
                            ProductCode = "204",
                            ProductName = "MasterCard Gold"
                        },
                        new
                        {
                            Id = 5,
                            ProductCode = "205",
                            ProductName = "Platinum Plus"
                        },
                        new
                        {
                            Id = 6,
                            ProductCode = "206",
                            ProductName = "Platinum Plus Metal"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SegmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentCode")
                        .IsUnique();

                    b.ToTable("SEGMENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SegmentCode = "OGR",
                            SegmentName = "Öğrenci"
                        },
                        new
                        {
                            Id = 2,
                            SegmentCode = "PER",
                            SegmentName = "Şirket Çalışanı"
                        },
                        new
                        {
                            Id = 3,
                            SegmentCode = "CFT",
                            SegmentName = "Çiftçi"
                        },
                        new
                        {
                            Id = 4,
                            SegmentCode = "EVH",
                            SegmentName = "Ev Hanımı"
                        },
                        new
                        {
                            Id = 5,
                            SegmentCode = "EMK",
                            SegmentName = "Emekli"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<long?>("OriginalTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Rrn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("TransactionCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OriginalTransactionId")
                        .IsUnique()
                        .HasFilter("[OriginalTransactionId] IS NOT NULL");

                    b.HasIndex("Rrn")
                        .IsUnique()
                        .HasFilter("[Rrn] IS NOT NULL");

                    b.HasIndex("TransactionCodeId");

                    b.HasIndex("CardId", "TransactionDate");

                    b.HasIndex("CustomerId", "TransactionDate");

                    b.ToTable("TRANSACTION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.TransactionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TRANSACTION_CODE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SA",
                            Name = "Satış"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NA",
                            Name = "Nakit Avans"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OD",
                            Name = "Borç Ödeme"
                        },
                        new
                        {
                            Id = 4,
                            Code = "IA",
                            Name = "İade"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignCondition", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Conditions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignMerchant", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignMerchants")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Merchant", "Merchant")
                        .WithMany("CampaignMerchants")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignParticipation", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Participations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Participations")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Participations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignProduct", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignProducts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("CampaignProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignReward", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Rewards")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Rewards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Rewards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignSegment", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignSegments")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Segment", "Segment")
                        .WithMany("CampaignSegments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignTransactionCode", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignTransactionCodes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.TransactionCode", "TransactionCode")
                        .WithMany("CampaignTransactionCodes")
                        .HasForeignKey("TransactionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("TransactionCode");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("Cards")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Segment", "Segment")
                        .WithMany("Customers")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.HasOne("CampaignSystem.Entities.MerchantCategory", "MerchantCategory")
                        .WithMany("Merchants")
                        .HasForeignKey("MerchantCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MerchantCategory");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Transaction", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Transaction", "OriginalTransaction")
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.TransactionCode", "TransactionCode")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Customer");

                    b.Navigation("Merchant");

                    b.Navigation("OriginalTransaction");

                    b.Navigation("TransactionCode");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignMerchants");

                    b.Navigation("CampaignProducts");

                    b.Navigation("CampaignSegments");

                    b.Navigation("CampaignTransactionCodes");

                    b.Navigation("Conditions");

                    b.Navigation("Participations");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Rewards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Participations");

                    b.Navigation("Rewards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.Navigation("CampaignMerchants");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.MerchantCategory", b =>
                {
                    b.Navigation("Merchants");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Product", b =>
                {
                    b.Navigation("CampaignProducts");

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Segment", b =>
                {
                    b.Navigation("CampaignSegments");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CampaignSystem.Entities.TransactionCode", b =>
                {
                    b.Navigation("CampaignTransactionCodes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
