// <auto-generated />
using System;
using CampaignSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampaignSystem.Data.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    [Migration("20260901083535_AddSeasonalPattern")]
    partial class AddSeasonalPattern
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampaignSystem.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CardType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EarningType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentBasis")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxRewardAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaximumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RefundClawbackDays")
                        .HasColumnType("int");

                    b.Property<bool>("RefundClawbackEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RewardPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UnusedPointsClawbackDays")
                        .HasColumnType("int");

                    b.Property<bool>("UnusedPointsClawbackEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UnusedPointsClawbackProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EndDate");

                    b.ToTable("CAMPAIGN", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignClawbackExemptProduct", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CAMPAIGN_CLAWBACK_EXEMPT_PRODUCT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CAMPAIGN_CONDITION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignConditionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CAMPAIGN_CONDITION_TEMPLATE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Key = "DateRange",
                            TemplateText = "Kampanya {StartDate} - {EndDate} tarihleri arasında geçerlidir."
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Key = "EnrollmentRequired",
                            TemplateText = "Kampanyadan yararlanabilmek için kampanyaya katılım sağlanması gerekmektedir."
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Key = "MinAndMaxAmount",
                            TemplateText = "İşlem tutarı {MinimumAmount} TL ile {MaximumAmount} TL arasında olmalıdır."
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Key = "MinAmountOnly",
                            TemplateText = "En az {MinimumAmount} TL tutarında işlem yapılması gerekmektedir."
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Key = "MaxAmountOnly",
                            TemplateText = "İşlem tutarı en fazla {MaximumAmount} TL olmalıdır."
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Key = "RewardPoint",
                            TemplateText = "Uygun her işlem için {RewardPoint} TL Worldpuan kazandırır."
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Key = "MaxRewardAmount",
                            TemplateText = "Kampanya kapsamında {PerUnit} başına en fazla {MaxRewardAmount} TL Worldpuan kazanılabilir."
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Key = "Gender",
                            TemplateText = "Kampanya yalnızca {GenderText} müşteriler için geçerlidir."
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Key = "CardType",
                            TemplateText = "Kampanya yalnızca {CardTypeText} kartlar için geçerlidir."
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Key = "SegmentList",
                            TemplateText = "Kampanya yalnızca şu müşteri gruplarına açıktır: {Names}."
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Key = "ProductList",
                            TemplateText = "Kampanya yalnızca şu kart tiplerinde geçerlidir: {Names}."
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Key = "MerchantList",
                            TemplateText = "Kampanya yalnızca şu üye işyerlerinde yapılan alışverişlerde geçerlidir: {Names}."
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Key = "TransactionCodeList",
                            TemplateText = "Kampanya yalnızca şu işlem türlerinde geçerlidir: {Names}."
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Key = "UnusedPointsClawback",
                            TemplateText = "Bu kampanyadan kazanılan kullanılmayan Worldpuanlar {ReclaimDate} tarihinde geri alınır."
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Key = "UnusedPointsClawbackExempt",
                            TemplateText = "Şu kart tipleri bu geri alım kuralından muaftır: {Names}."
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignMerchant", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "MerchantId");

                    b.HasIndex("MerchantId");

                    b.ToTable("CAMPAIGN_MERCHANT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignParticipation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParticipationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId", "CardId")
                        .IsUnique();

                    b.ToTable("CAMPAIGN_PARTICIPATION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignProduct", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CAMPAIGN_PRODUCT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignReward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("QualifyingCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RewardDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RewardPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId", "CardId")
                        .IsUnique()
                        .HasFilter("[RewardType] = 'Earn'");

                    b.ToTable("CAMPAIGN_REWARD", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignSegment", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "SegmentId");

                    b.HasIndex("SegmentId");

                    b.ToTable("CAMPAIGN_SEGMENT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignTransactionCode", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionCodeId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "TransactionCodeId");

                    b.HasIndex("TransactionCodeId");

                    b.ToTable("CAMPAIGN_TRANSACTION_CODE", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CARD", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("SegmentId");

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MerchantCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MerchantNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantCategoryId");

                    b.HasIndex("MerchantNumber")
                        .IsUnique();

                    b.ToTable("MERCHANT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MerchantCategoryId = 2,
                            MerchantName = "Grande Cafe",
                            MerchantNumber = "300145782"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MerchantCategoryId = 2,
                            MerchantName = "Köfteci Yusuf",
                            MerchantNumber = "300912467"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            MerchantCategoryId = 2,
                            MerchantName = "Big Chefs",
                            MerchantNumber = "300558214"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MerchantCategoryId = 3,
                            MerchantName = "Opet",
                            MerchantNumber = "410874193"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MerchantCategoryId = 3,
                            MerchantName = "Shell",
                            MerchantNumber = "410336729"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MerchantCategoryId = 3,
                            MerchantName = "Petrol Ofisi",
                            MerchantNumber = "410771056"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            MerchantCategoryId = 1,
                            MerchantName = "Migros",
                            MerchantNumber = "520419863"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            MerchantCategoryId = 1,
                            MerchantName = "BİM",
                            MerchantNumber = "520684137"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            MerchantCategoryId = 1,
                            MerchantName = "A101",
                            MerchantNumber = "520297540"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            MerchantCategoryId = 7,
                            MerchantName = "Teknosa",
                            MerchantNumber = "610853024"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            MerchantCategoryId = 7,
                            MerchantName = "Vatan Bilgisayar",
                            MerchantNumber = "610140678"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            MerchantCategoryId = 4,
                            MerchantName = "LC Waikiki",
                            MerchantNumber = "710962385"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.MerchantCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("MERCHANT_CATEGORY", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "GDA",
                            CategoryName = "Gıda / Market"
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "RST",
                            CategoryName = "Restoran / Yeme-İçme"
                        },
                        new
                        {
                            Id = 3,
                            CategoryCode = "AKY",
                            CategoryName = "Akaryakıt"
                        },
                        new
                        {
                            Id = 4,
                            CategoryCode = "GYM",
                            CategoryName = "Giyim"
                        },
                        new
                        {
                            Id = 5,
                            CategoryCode = "AYK",
                            CategoryName = "Ayakkabı & Aksesuar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryCode = "KOZ",
                            CategoryName = "Kozmetik"
                        },
                        new
                        {
                            Id = 7,
                            CategoryCode = "ELK",
                            CategoryName = "Elektronik"
                        },
                        new
                        {
                            Id = 8,
                            CategoryCode = "TEL",
                            CategoryName = "Telekomünikasyon / GSM"
                        },
                        new
                        {
                            Id = 9,
                            CategoryCode = "MOB",
                            CategoryName = "Mobilya & Ev Tekstili"
                        },
                        new
                        {
                            Id = 10,
                            CategoryCode = "BYZ",
                            CategoryName = "Beyaz Eşya"
                        },
                        new
                        {
                            Id = 11,
                            CategoryCode = "OTO",
                            CategoryName = "Otomotiv & Oto Bakım"
                        },
                        new
                        {
                            Id = 12,
                            CategoryCode = "ARK",
                            CategoryName = "Araç Kiralama"
                        },
                        new
                        {
                            Id = 13,
                            CategoryCode = "TUR",
                            CategoryName = "Turizm / Seyahat / Otel"
                        },
                        new
                        {
                            Id = 14,
                            CategoryCode = "HVY",
                            CategoryName = "Havayolları / Ulaşım"
                        },
                        new
                        {
                            Id = 15,
                            CategoryCode = "EGT",
                            CategoryName = "Eğitim"
                        },
                        new
                        {
                            Id = 16,
                            CategoryCode = "SGL",
                            CategoryName = "Sağlık / Eczane / Optik"
                        },
                        new
                        {
                            Id = 17,
                            CategoryCode = "SGR",
                            CategoryName = "Sigorta"
                        },
                        new
                        {
                            Id = 18,
                            CategoryCode = "SPR",
                            CategoryName = "Spor"
                        },
                        new
                        {
                            Id = 19,
                            CategoryCode = "KUY",
                            CategoryName = "Kuyumculuk / Saat"
                        },
                        new
                        {
                            Id = 20,
                            CategoryCode = "KRT",
                            CategoryName = "Kırtasiye / Oyuncak"
                        },
                        new
                        {
                            Id = 21,
                            CategoryCode = "YPI",
                            CategoryName = "Yapı & İnşaat"
                        },
                        new
                        {
                            Id = 22,
                            CategoryCode = "EGL",
                            CategoryName = "Eğlence"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("PRODUCT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductCode = "201",
                            ProductName = "Visa Classic"
                        },
                        new
                        {
                            Id = 2,
                            ProductCode = "202",
                            ProductName = "MasterCard Classic"
                        },
                        new
                        {
                            Id = 3,
                            ProductCode = "203",
                            ProductName = "Visa Gold"
                        },
                        new
                        {
                            Id = 4,
                            ProductCode = "204",
                            ProductName = "MasterCard Gold"
                        },
                        new
                        {
                            Id = 5,
                            ProductCode = "205",
                            ProductName = "Platinum Plus"
                        },
                        new
                        {
                            Id = 6,
                            ProductCode = "206",
                            ProductName = "Platinum Plus Metal"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.SeasonalPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MerchantCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantCategoryId", "Month")
                        .IsUnique();

                    b.ToTable("SEASONAL_PATTERN", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MerchantCategoryId = 3,
                            Month = 1,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 2,
                            MerchantCategoryId = 3,
                            Month = 2,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 3,
                            MerchantCategoryId = 3,
                            Month = 6,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 4,
                            MerchantCategoryId = 3,
                            Month = 7,
                            Weight = 1.35m
                        },
                        new
                        {
                            Id = 5,
                            MerchantCategoryId = 3,
                            Month = 8,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 6,
                            MerchantCategoryId = 3,
                            Month = 9,
                            Weight = 1.05m
                        },
                        new
                        {
                            Id = 7,
                            MerchantCategoryId = 3,
                            Month = 12,
                            Weight = 0.95m
                        },
                        new
                        {
                            Id = 8,
                            MerchantCategoryId = 4,
                            Month = 1,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 9,
                            MerchantCategoryId = 4,
                            Month = 2,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 10,
                            MerchantCategoryId = 4,
                            Month = 3,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 11,
                            MerchantCategoryId = 4,
                            Month = 4,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 12,
                            MerchantCategoryId = 4,
                            Month = 7,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 13,
                            MerchantCategoryId = 4,
                            Month = 9,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 14,
                            MerchantCategoryId = 4,
                            Month = 10,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 15,
                            MerchantCategoryId = 4,
                            Month = 11,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 16,
                            MerchantCategoryId = 4,
                            Month = 12,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 17,
                            MerchantCategoryId = 5,
                            Month = 3,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 18,
                            MerchantCategoryId = 5,
                            Month = 4,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 19,
                            MerchantCategoryId = 5,
                            Month = 7,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 20,
                            MerchantCategoryId = 5,
                            Month = 9,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 21,
                            MerchantCategoryId = 5,
                            Month = 10,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 22,
                            MerchantCategoryId = 5,
                            Month = 11,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 23,
                            MerchantCategoryId = 5,
                            Month = 12,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 24,
                            MerchantCategoryId = 7,
                            Month = 1,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 25,
                            MerchantCategoryId = 7,
                            Month = 2,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 26,
                            MerchantCategoryId = 7,
                            Month = 3,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 27,
                            MerchantCategoryId = 7,
                            Month = 8,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 28,
                            MerchantCategoryId = 7,
                            Month = 9,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 29,
                            MerchantCategoryId = 7,
                            Month = 11,
                            Weight = 1.55m
                        },
                        new
                        {
                            Id = 30,
                            MerchantCategoryId = 7,
                            Month = 12,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 31,
                            MerchantCategoryId = 9,
                            Month = 1,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 32,
                            MerchantCategoryId = 9,
                            Month = 2,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 33,
                            MerchantCategoryId = 9,
                            Month = 5,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 34,
                            MerchantCategoryId = 9,
                            Month = 6,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 35,
                            MerchantCategoryId = 9,
                            Month = 7,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 36,
                            MerchantCategoryId = 9,
                            Month = 9,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 37,
                            MerchantCategoryId = 9,
                            Month = 11,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 38,
                            MerchantCategoryId = 10,
                            Month = 1,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 39,
                            MerchantCategoryId = 10,
                            Month = 2,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 40,
                            MerchantCategoryId = 10,
                            Month = 5,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 41,
                            MerchantCategoryId = 10,
                            Month = 6,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 42,
                            MerchantCategoryId = 10,
                            Month = 7,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 43,
                            MerchantCategoryId = 10,
                            Month = 11,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 44,
                            MerchantCategoryId = 10,
                            Month = 12,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 45,
                            MerchantCategoryId = 13,
                            Month = 1,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 46,
                            MerchantCategoryId = 13,
                            Month = 2,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 47,
                            MerchantCategoryId = 13,
                            Month = 3,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 48,
                            MerchantCategoryId = 13,
                            Month = 6,
                            Weight = 1.35m
                        },
                        new
                        {
                            Id = 49,
                            MerchantCategoryId = 13,
                            Month = 7,
                            Weight = 1.55m
                        },
                        new
                        {
                            Id = 50,
                            MerchantCategoryId = 13,
                            Month = 8,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 51,
                            MerchantCategoryId = 13,
                            Month = 9,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 52,
                            MerchantCategoryId = 13,
                            Month = 11,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 53,
                            MerchantCategoryId = 13,
                            Month = 12,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 54,
                            MerchantCategoryId = 14,
                            Month = 1,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 55,
                            MerchantCategoryId = 14,
                            Month = 2,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 56,
                            MerchantCategoryId = 14,
                            Month = 6,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 57,
                            MerchantCategoryId = 14,
                            Month = 7,
                            Weight = 1.45m
                        },
                        new
                        {
                            Id = 58,
                            MerchantCategoryId = 14,
                            Month = 8,
                            Weight = 1.4m
                        },
                        new
                        {
                            Id = 59,
                            MerchantCategoryId = 14,
                            Month = 11,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 60,
                            MerchantCategoryId = 14,
                            Month = 12,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 61,
                            MerchantCategoryId = 15,
                            Month = 1,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 62,
                            MerchantCategoryId = 15,
                            Month = 2,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 63,
                            MerchantCategoryId = 15,
                            Month = 4,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 64,
                            MerchantCategoryId = 15,
                            Month = 5,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 65,
                            MerchantCategoryId = 15,
                            Month = 6,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 66,
                            MerchantCategoryId = 15,
                            Month = 7,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 67,
                            MerchantCategoryId = 15,
                            Month = 8,
                            Weight = 1.45m
                        },
                        new
                        {
                            Id = 68,
                            MerchantCategoryId = 15,
                            Month = 9,
                            Weight = 1.6m
                        },
                        new
                        {
                            Id = 69,
                            MerchantCategoryId = 15,
                            Month = 10,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 70,
                            MerchantCategoryId = 15,
                            Month = 11,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 71,
                            MerchantCategoryId = 15,
                            Month = 12,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 72,
                            MerchantCategoryId = 18,
                            Month = 1,
                            Weight = 1.45m
                        },
                        new
                        {
                            Id = 73,
                            MerchantCategoryId = 18,
                            Month = 2,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 74,
                            MerchantCategoryId = 18,
                            Month = 6,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 75,
                            MerchantCategoryId = 18,
                            Month = 7,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 76,
                            MerchantCategoryId = 18,
                            Month = 8,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 77,
                            MerchantCategoryId = 18,
                            Month = 9,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 78,
                            MerchantCategoryId = 18,
                            Month = 10,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 79,
                            MerchantCategoryId = 19,
                            Month = 2,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 80,
                            MerchantCategoryId = 19,
                            Month = 4,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 81,
                            MerchantCategoryId = 19,
                            Month = 5,
                            Weight = 1.35m
                        },
                        new
                        {
                            Id = 82,
                            MerchantCategoryId = 19,
                            Month = 6,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 83,
                            MerchantCategoryId = 19,
                            Month = 7,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 84,
                            MerchantCategoryId = 19,
                            Month = 8,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 85,
                            MerchantCategoryId = 19,
                            Month = 9,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 86,
                            MerchantCategoryId = 19,
                            Month = 11,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 87,
                            MerchantCategoryId = 19,
                            Month = 12,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 88,
                            MerchantCategoryId = 20,
                            Month = 1,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 89,
                            MerchantCategoryId = 20,
                            Month = 2,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 90,
                            MerchantCategoryId = 20,
                            Month = 4,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 91,
                            MerchantCategoryId = 20,
                            Month = 5,
                            Weight = 0.85m
                        },
                        new
                        {
                            Id = 92,
                            MerchantCategoryId = 20,
                            Month = 6,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 93,
                            MerchantCategoryId = 20,
                            Month = 7,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 94,
                            MerchantCategoryId = 20,
                            Month = 8,
                            Weight = 1.55m
                        },
                        new
                        {
                            Id = 95,
                            MerchantCategoryId = 20,
                            Month = 9,
                            Weight = 1.6m
                        },
                        new
                        {
                            Id = 96,
                            MerchantCategoryId = 20,
                            Month = 10,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 97,
                            MerchantCategoryId = 20,
                            Month = 12,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 98,
                            MerchantCategoryId = 21,
                            Month = 1,
                            Weight = 0.75m
                        },
                        new
                        {
                            Id = 99,
                            MerchantCategoryId = 21,
                            Month = 2,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 100,
                            MerchantCategoryId = 21,
                            Month = 4,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 101,
                            MerchantCategoryId = 21,
                            Month = 5,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 102,
                            MerchantCategoryId = 21,
                            Month = 6,
                            Weight = 1.35m
                        },
                        new
                        {
                            Id = 103,
                            MerchantCategoryId = 21,
                            Month = 7,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 104,
                            MerchantCategoryId = 21,
                            Month = 8,
                            Weight = 1.25m
                        },
                        new
                        {
                            Id = 105,
                            MerchantCategoryId = 21,
                            Month = 9,
                            Weight = 1.15m
                        },
                        new
                        {
                            Id = 106,
                            MerchantCategoryId = 21,
                            Month = 12,
                            Weight = 0.8m
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SegmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentCode")
                        .IsUnique();

                    b.ToTable("SEGMENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SegmentCode = "OGR",
                            SegmentName = "Öğrenci"
                        },
                        new
                        {
                            Id = 2,
                            SegmentCode = "PER",
                            SegmentName = "Şirket Çalışanı"
                        },
                        new
                        {
                            Id = 3,
                            SegmentCode = "CFT",
                            SegmentName = "Çiftçi"
                        },
                        new
                        {
                            Id = 4,
                            SegmentCode = "EVH",
                            SegmentName = "Ev Hanımı"
                        },
                        new
                        {
                            Id = 5,
                            SegmentCode = "EMK",
                            SegmentName = "Emekli"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClawbackProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<long?>("OriginalTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Rrn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("TransactionCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClawbackProcessedAt")
                        .HasFilter("[ClawbackProcessedAt] IS NULL AND [OriginalTransactionId] IS NOT NULL");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OriginalTransactionId");

                    b.HasIndex("Rrn")
                        .IsUnique()
                        .HasFilter("[Rrn] IS NOT NULL");

                    b.HasIndex("TransactionCodeId");

                    b.HasIndex("CardId", "TransactionDate");

                    b.HasIndex("CustomerId", "TransactionDate");

                    b.ToTable("TRANSACTION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.TransactionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TRANSACTION_CODE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SA",
                            Name = "Satış"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NA",
                            Name = "Nakit Avans"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OD",
                            Name = "Borç Ödeme"
                        },
                        new
                        {
                            Id = 4,
                            Code = "IA",
                            Name = "İade"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PS",
                            Name = "Puan Harcama"
                        });
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignClawbackExemptProduct", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("ClawbackExemptProducts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("ClawbackExemptCampaigns")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignCondition", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Conditions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignMerchant", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignMerchants")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Merchant", "Merchant")
                        .WithMany("CampaignMerchants")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignParticipation", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Participations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Participations")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Participations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignProduct", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignProducts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("CampaignProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignReward", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Rewards")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Rewards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Rewards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignSegment", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignSegments")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Segment", "Segment")
                        .WithMany("CampaignSegments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignTransactionCode", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignTransactionCodes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.TransactionCode", "TransactionCode")
                        .WithMany("CampaignTransactionCodes")
                        .HasForeignKey("TransactionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("TransactionCode");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("Cards")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Segment", "Segment")
                        .WithMany("Customers")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.HasOne("CampaignSystem.Entities.MerchantCategory", "MerchantCategory")
                        .WithMany("Merchants")
                        .HasForeignKey("MerchantCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MerchantCategory");
                });

            modelBuilder.Entity("CampaignSystem.Entities.SeasonalPattern", b =>
                {
                    b.HasOne("CampaignSystem.Entities.MerchantCategory", "MerchantCategory")
                        .WithMany("SeasonalPatterns")
                        .HasForeignKey("MerchantCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchantCategory");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Transaction", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Transaction", "OriginalTransaction")
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.TransactionCode", "TransactionCode")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Customer");

                    b.Navigation("Merchant");

                    b.Navigation("OriginalTransaction");

                    b.Navigation("TransactionCode");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignMerchants");

                    b.Navigation("CampaignProducts");

                    b.Navigation("CampaignSegments");

                    b.Navigation("CampaignTransactionCodes");

                    b.Navigation("ClawbackExemptProducts");

                    b.Navigation("Conditions");

                    b.Navigation("Participations");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Rewards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Participations");

                    b.Navigation("Rewards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.Navigation("CampaignMerchants");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.MerchantCategory", b =>
                {
                    b.Navigation("Merchants");

                    b.Navigation("SeasonalPatterns");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Product", b =>
                {
                    b.Navigation("CampaignProducts");

                    b.Navigation("Cards");

                    b.Navigation("ClawbackExemptCampaigns");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Segment", b =>
                {
                    b.Navigation("CampaignSegments");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CampaignSystem.Entities.TransactionCode", b =>
                {
                    b.Navigation("CampaignTransactionCodes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
