// <auto-generated />
using System;
using CampaignSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampaignSystem.Data.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampaignSystem.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EarningType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxRewardAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaximumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("RewardPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EndDate");

                    b.ToTable("CAMPAIGN", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignMerchant", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "MerchantId");

                    b.HasIndex("MerchantId");

                    b.ToTable("CAMPAIGN_MERCHANT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignParticipation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParticipationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId", "CardId")
                        .IsUnique();

                    b.ToTable("CAMPAIGN_PARTICIPATION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignProduct", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CAMPAIGN_PRODUCT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignReward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("QualifyingCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RewardDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RewardPoint")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CampaignId", "CustomerId", "CardId")
                        .IsUnique();

                    b.ToTable("CAMPAIGN_REWARD", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignSegment", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "SegmentId");

                    b.HasIndex("SegmentId");

                    b.ToTable("CAMPAIGN_SEGMENT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignTransactionCode", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionCodeId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "TransactionCodeId");

                    b.HasIndex("TransactionCodeId");

                    b.ToTable("CAMPAIGN_TRANSACTION_CODE", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CARD", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("SegmentId");

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MerchantNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantNumber")
                        .IsUnique();

                    b.ToTable("MERCHANT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("PRODUCT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SegmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SegmentCode")
                        .IsUnique();

                    b.ToTable("SEGMENT", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("Rrn")
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("TransactionCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Rrn")
                        .IsUnique()
                        .HasFilter("[Rrn] IS NOT NULL");

                    b.HasIndex("TransactionCodeId");

                    b.HasIndex("CardId", "TransactionDate");

                    b.HasIndex("CustomerId", "TransactionDate");

                    b.ToTable("TRANSACTION", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.TransactionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TRANSACTION_CODE", (string)null);
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignMerchant", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignMerchants")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Merchant", "Merchant")
                        .WithMany("CampaignMerchants")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignParticipation", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Participations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Participations")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Participations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignProduct", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignProducts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("CampaignProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignReward", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("Rewards")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Rewards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Rewards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Card");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignSegment", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignSegments")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Segment", "Segment")
                        .WithMany("CampaignSegments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CampaignSystem.Entities.CampaignTransactionCode", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Campaign", "Campaign")
                        .WithMany("CampaignTransactionCodes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.TransactionCode", "TransactionCode")
                        .WithMany("CampaignTransactionCodes")
                        .HasForeignKey("TransactionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("TransactionCode");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Product", "Product")
                        .WithMany("Cards")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Segment", "Segment")
                        .WithMany("Customers")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Transaction", b =>
                {
                    b.HasOne("CampaignSystem.Entities.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampaignSystem.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampaignSystem.Entities.TransactionCode", "TransactionCode")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Customer");

                    b.Navigation("Merchant");

                    b.Navigation("TransactionCode");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignMerchants");

                    b.Navigation("CampaignProducts");

                    b.Navigation("CampaignSegments");

                    b.Navigation("CampaignTransactionCodes");

                    b.Navigation("Participations");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Card", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Rewards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Customer", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Participations");

                    b.Navigation("Rewards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Merchant", b =>
                {
                    b.Navigation("CampaignMerchants");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Product", b =>
                {
                    b.Navigation("CampaignProducts");

                    b.Navigation("Cards");
                });

            modelBuilder.Entity("CampaignSystem.Entities.Segment", b =>
                {
                    b.Navigation("CampaignSegments");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CampaignSystem.Entities.TransactionCode", b =>
                {
                    b.Navigation("CampaignTransactionCodes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
